# syntax errors -> occurs when program doesn't follow correct Python syntaxes or rules.
print("hello, user)    # SyntaxError: unterminated string literal
print("hello, user"    # SyntaxError: '(' was never closed
      
# runtime errors -> these errors will show up during run time i.e. after executing the program when the particular line with an error gets executed.
#                -> usually 3 types - TypeError, NameError, ValueError
prin("Hello, User")    # NameError: name 'prin' is not defined
print(true + false)    # NameError: name 'true is not defined
print("true" + 5)      # TypeError: can only concatenate str (not "int") to str
a, b = [1,3,4]         # ValueError: too many values to unpack (expected 2)
      
# logical errors -> which completely to the user and their requirements, no actual error generated by program but the output does the match the expected result.
# calculate no of days in a leap year
print(31 + 28 + 31 + 30 + 31 + 30 + 31 + 31 + 30 + 31 + 30 + 31)
# expected output -> 366
# actual output -> 365
